export const treningsØvelser = [
  "Pushups",
  "Situps",
  "Squats",
  "Burpees",
  "Lunges",
  "Mountain climbers",
  "Plank",
  "Jumping jacks",
  "Wall sit",
  "Triceps dips",
  "High knees",
  "Side plank",
  "Calf raises",
  "Superman",
  "Glute bridge",
  "Bicycle crunches",
  "Russian twist",
  "Leg raises",
  "Heel touches",
  "Arm circles",
  "Flutter kicks",
  "Scissor kicks",
  "Arm circles",
];
