export const treningsØvelser = [
  "Hallo, treningskrigere! :muscle: I dag er det tid for Squat Challenge! :leg: Er du klar til å synke dypt og stige til nye høyder? \nDitt mål: fullfør så mange squats som mulig før kl. 17:00! :clock5: La oss se hvem som er dagens squat-konge eller -dronning! :crown: Husk, hver squat teller i vår jakt på styrke og utholdenhet! :fire: #SquatChallenge #StrengthAndHonor #TeamPower :muscle:",
  "God morgen, plank-helter! :sunrise: Klar for dagens Plank Challenge? :straight_ruler: \nLa oss holde planken så lenge vi kan før lunsj! :sandwich: Kan du slå din egen rekord? :stopwatch: Husk, det er ikke bare en utfordring, det er en reise mot kjernestyrke! :earth_americas: #PlankChallenge #CoreWarriors #StayStrong :muscle:",
  "Hey hoppeglade venner! :rabbit: Det er tid for Jumping Jacks Challenge! :person_jumping: \nHopp inn i dagen og fullfør så mange jumping jacks som mulig før formiddagen 12:00! :coffee: La oss hoppe høyere og sterkere sammen! #JumpingJacksChallenge #HopTilYouDrop #EnergyBoost :zap:",
  "Kjære lunge-legender! :runner: Steg inn i dagens Lunge Challenge med stil! :dancer: \nDitt mål: utfør så mange lunges som mulig før arbeidsdagen er over. :office: Vis styrke og balanse, og bli dagens lunge-mester! :medal_sports: #LungeChallenge #BalanceAndStrength #LegDayEveryDay :leg:",
  "Oppmerksomhet, burpee-brigade! :firefighter: I dag er det Burpee Challenge! :person_lifting_weights: Klar for å hoppe, knebøy og push-up gjennom dagen? \nDitt mål: knus så mange burpees som mulig før solnedgang! :sunset: La oss se hvem som er den ultimate burpee-bossen! :muscle: #BurpeeChallenge #FullBodyWorkout #NoLimits :boom:",
  "Heisann, yoga-yogier! :person_in_lotus_position: Tid for dagens Yoga Challenge! :sun_with_face: Finn ditt zen og utfør så mange yoga-poser som mulig før kveldste! :tea: \nLa oss strekke oss mot fred og fleksibilitet sammen! #YogaChallenge #PeaceAndFlexibility #ZenModeOn :peace_symbol:",
  "God dag, løpe-entusiaster! :running_shirt_with_sash: \nKlar for dagens Running Challenge? :running: Sett ditt mål for distanse og løp den før middag! :fork_and_knife: La oss jage hastigheten og utholdenheten sammen! #RunningChallenge #MilesForSmiles #SpeedAndEndurance :dash:",
];
// export const treningsØvelser = [
//   "Hei superhelt! :rocket: Dagens fit-challenge er her! :muscle: Klar for å brette opp ermene og ta tak i **push-up** oppgaven? :man-lifting-weights: Ditt mål: knus så mange push-ups du kan før klokken slår 15:00! :clock3: **Slik gjør du**: Start i plankeposisjon med hendene skulderbredde fra hverandre. Senk kroppen ned ved å bøye i albueleddene, før du presser opp igjen. :star2: Husk, den som går all in og knuser flest push-ups er dagens ultimate vinner! :trophy: #PushUpChallenge #FitFam #LetsCrushIt :rocket:",
//   "Hei treningsvenner! :sunny: Klar for dagens **squat** utfordring? :leg: Målet ditt er å utføre så mange squats som mulig før 17:00! :clock5: **Slik gjør du**: Stå med føttene skulderbredde fra hverandre. Senk kroppen som om du skal sette deg på en stol, og sørg for at knærne ikke går forbi tærne. Press opp igjen. :fire: Vis hva du er laget av og bli dagens squat-mester! :trophy: #SquatChallenge #StrengthAndHonor :muscle:",
//   "Klar for en kjernemuskelutfordring? :zap: **Plank** utfordringen starter nå! :man-lifting-weights: Se hvor lenge du kan holde planken, men vi teller i repetisjoner av 30 sekunder før kl. 15:00! :clock3: **Slik gjør du**: Start i en plankeposisjon på albuene med kroppen i en rett linje fra hode til tå. Hold stillingen med magemusklene strammet. :star2: Den med flest '30-sekunders hold' vinner! :trophy: #PlankChallenge #CoreStrength :fire:",
//   "Tid for **utfall**! :runner: Dagens mål: Gjennomfør så mange utfall som mulig før dagen er omme. :sun_with_face: **Slik gjør du**: Ta et stort skritt frem med det ene benet og senk kroppen ned så begge knær danner en vinkel på 90 grader. Bytt ben og gjenta. :muscle: La oss se hvem som har den beste utholdenheten! :trophy: #LungeChallenge #Endurance :leg:",
//   "Dagens utfordring: **Burpees**! :fire: Er du klar til å hoppe inn i det og gi alt? :rabbit: Målet er å gjøre så mange burpees du kan før 15:00! :clock3: **Slik gjør du**: Start i stående stilling, gå ned i en squat, sett hendene i gulvet, spark føttene bak til en plankeposisjon, gjør en push-up, hopp føttene tilbake til hendene og avslutt med et hopp opp. :star2: Hvem blir burpee-kongen eller -dronningen i dag? :trophy: #BurpeeChallenge #TotalBodyWorkout :boom:",
//   "Klar for dagens **armhevinger** utfordring? :muscle: La oss se hvor mange armhevinger du kan utføre før klokken slår 15:00! :clock3: **Slik gjør du**: Plasser hendene litt bredere enn skulderbredde fra hverandre. Senk kroppen ned til brystet nesten berører gulvet, hold kroppen rett hele veien. Press opp igjen. :star2: Konkurrer mot deg selv og resten av teamet for å se hvem som er den sterkeste! :trophy: #PushUpPower #BeStrong :rocket:",
//   "Er du klar for en **kjerne**-utfordring med **sit-ups**? :zap: Målet er å fullføre så mange sit-ups som mulig før 17:00! :clock5: **Slik gjør du**: Ligg på ryggen med bøyde knær og føttene flatt på gulvet. Kryss armene foran brystet og løft overkroppen opp mot knærne, senk deretter kontrollert ned igjen. :fire: Hvem blir kjerne-styrke mesteren i dag? :trophy: #CoreChallenge #SitUps :muscle:",
//   "Tid for litt **bein** styrke med **knebøy**! :leg: Dagens utfordring er å fullføre så mange knebøy som mulig før dagen er omme. :sun_with_face: **Slik gjør du**: Stå rett med føttene skulderbreddes avstand. Senk kroppen som om du skal sette deg på en usynlig stol, sørg for å holde ryggen rett. Gå tilbake til startposisjon. :star2: La oss se hvem som er den sterkeste i knebøy! :trophy: #SquatStrong #LegDay :leg:",
//   "Gjør deg klar for **rygg** styrke med **supermann** øvelsen! :superhero: Dagens mål er å holde supermann posisjonen i så mange repetisjoner av 30 sekunder som mulig før 15:00! :clock3: **Slik gjør du**: Ligg med ansiktet ned på gulvet, strekk ut armer og ben. Løft armer og ben opp fra gulvet samtidig, hold posisjonen, og senk ned igjen. :star2: Vis din indre superhelt og styrk ryggen! :trophy: #SupermanChallenge #BackStrength :muscle:",
//   "La oss få opp pulsen med **hoppetau**! :jump_rope: Se hvor mange minutter du kan hoppe tau uten stopp før klokken slår 17:00! :clock5: **Slik gjør du**: Hold hoppetauet med hendene og sving det over hodet ditt og under føttene i en jevn rytme. Hold deg lett på tå og hold opp tempoet. :fire: Hvem kan hoppe lengst og holde pulsen oppe? :trophy: #JumpRopeChallenge #CardioBlast :heartbeat:",
//   "Dagens balanseutfordring er **stå på ett ben**! :flamingo: Se hvor lenge du kan holde balansen på ett ben, vi teller antall forsøk av 30 sekunder før 15:00! :clock3: **Slik gjør du**: Stå rett opp, løft det ene benet fra gulvet og hold balansen så lenge du kan. Bytt ben etter hvert forsøk. :star2: Balanse er nøkkelen! Hvem har best stabilitet i dag? :trophy: #BalanceChallenge #SteadyAsARock :mountain:",
// ];

// "Pushups",
// "Situps",
// "Squats",
// "Burpees",
// "Lunges",
// "Mountain climbers",
// "Plank",
// "Jumping jacks",
// "Wall sit",
// "Triceps dips",
// "High knees",
// "Side plank",
// "Calf raises",
// "Superman",
// "Glute bridge",
// "Bicycle crunches",
// "Russian twist",
// "Leg raises",
// "Heel touches",
// "Arm circles",
// "Flutter kicks",
// "Scissor kicks",
// "Arm circles",
