export const treningsØvelser = [
  "Hallo, treningskrigere! :muscle: I dag er det tid for Squat Challenge! :leg: Er du klar til å synke dypt og stige til nye høyder? Ditt mål: fullfør så mange squats som mulig før kl. 17:00! :clock5: La oss se hvem som er dagens squat-konge eller -dronning! :crown: Husk, hver squat teller i vår jakt på styrke og utholdenhet! :fire: #SquatChallenge #StrengthAndHonor #TeamPower :muscle:",
  "God morgen, plank-helter! :sunrise: Klar for dagens Plank Challenge? :straight_ruler: La oss holde planken så lenge vi kan før lunsj! :sandwich: Kan du slå din egen rekord? :stopwatch: Husk, det er ikke bare en utfordring, det er en reise mot kjernestyrke! :earth_americas: #PlankChallenge #CoreWarriors #StayStrong :muscle:",
  "Hey hoppeglade venner! :rabbit: Det er tid for Jumping Jacks Challenge! :person_jumping: Hopp inn i dagen og fullfør så mange jumping jacks som mulig før kaffepausen kl. 10:00! :coffee: La oss hoppe høyere og sterkere sammen! #JumpingJacksChallenge #HopTilYouDrop #EnergyBoost :zap:",
  "Kjære lunge-legender! :runner: Steg inn i dagens Lunge Challenge med stil! :dancer: Ditt mål: utfør så mange lunges som mulig før arbeidsdagen er over. :office: Vis styrke og balanse, og bli dagens lunge-mester! :medal_sports: #LungeChallenge #BalanceAndStrength #LegDayEveryDay :leg:",
  "Oppmerksomhet, burpee-brigade! :firefighter: I dag er det Burpee Challenge! :person_lifting_weights: Klar for å hoppe, knebøy og push-up gjennom dagen? Ditt mål: knus så mange burpees som mulig før solnedgang! :sunset: La oss se hvem som er den ultimate burpee-bossen! :muscle: #BurpeeChallenge #FullBodyWorkout #NoLimits :boom:",
  "Heisann, yoga-yogier! :person_in_lotus_position: Tid for dagens Yoga Challenge! :sun_with_face: Finn ditt zen og utfør så mange yoga-poser som mulig før kveldste! :tea: La oss strekke oss mot fred og fleksibilitet sammen! #YogaChallenge #PeaceAndFlexibility #ZenModeOn :peace_symbol:",
  "God dag, løpe-entusiaster! :running_shirt_with_sash: Klar for dagens Running Challenge? :running: Sett ditt mål for distanse og løp den før middag! :fork_and_knife: La oss jage hastigheten og utholdenheten sammen! #RunningChallenge #MilesForSmiles #SpeedAndEndurance :dash:",
];

// "Pushups",
// "Situps",
// "Squats",
// "Burpees",
// "Lunges",
// "Mountain climbers",
// "Plank",
// "Jumping jacks",
// "Wall sit",
// "Triceps dips",
// "High knees",
// "Side plank",
// "Calf raises",
// "Superman",
// "Glute bridge",
// "Bicycle crunches",
// "Russian twist",
// "Leg raises",
// "Heel touches",
// "Arm circles",
// "Flutter kicks",
// "Scissor kicks",
// "Arm circles",
